name = "meno"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Meno"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.26.0"

[[lean_lib]]
name = "Meno"
